# Generated by Django 4.1 on 2023-10-21 04:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя студента')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия студента')),
                ('location', models.CharField(max_length=100, verbose_name='местоположение')),
                ('education', models.CharField(choices=[('НЕОКОЧЕННОЕ СРЕДНЕЕ', 'Incomplete Secondary'), ('СРЕДНЕЕ', 'Completed Secondary'), ('СРЕДНЕЕ ПРОФЕССИОНАЛЬНОЕ', 'Secondary Professional'), ('НЕОКОЧЕННОЕ ВЫСШЕЕ', 'Incomplete Higher'), ('ВЫСШЕЕ', 'Completed Higher')], default='СРЕДНЕЕ', max_length=100, verbose_name='уровень образования')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='специальность')),
                ('course_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='курсы ЯП'), blank=True, size=None)),
                ('hard_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='стек/навыки'), blank=True, size=None)),
                ('status', models.CharField(max_length=100, verbose_name='статус в трекере')),
                ('image', models.ImageField(blank=True, upload_to='students/images', verbose_name='фото студента')),
            ],
        ),
    ]
