# Generated by Django 4.1 on 2023-10-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название курса')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='слаг курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='навыки студента')),
            ],
            options={
                'verbose_name': 'навык',
                'verbose_name_plural': 'навыки',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя студента')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия студента')),
                ('location', models.CharField(max_length=150, verbose_name='местоположение')),
                ('education', models.CharField(choices=[('НЕОКОНЧЕННОЕ СРЕДНЕЕ', 'Incomplete Secondary'), ('СРЕДНЕЕ', 'Completed Secondary'), ('СРЕДНЕЕ ПРОФЕССИОНАЛЬНОЕ', 'Secondary Professional'), ('НЕОКОНЧЕННОЕ ВЫСШЕЕ', 'Incomplete Higher'), ('ВЫСШЕЕ', 'Completed Higher')], default='СРЕДНЕЕ', max_length=150, verbose_name='уровень образования')),
                ('specialty', models.CharField(max_length=150, verbose_name='специальность')),
                ('status', models.CharField(choices=[('АКТИВНО ИЩУ РАБОТУ', 'Actively Searching'), ('РАССМАТРИВАЮ ВХОДЯЩИЕ ПРЕДЛОЖЕНИЯ', 'Incoming Offers'), ('РАССМАТРИВАЮ ТОЛЬКО СТАЖИРОВКИ', 'Internship Only'), ('НЕ ИЩУ РАБОТУ', 'Not Searching'), ('ТРУДОУСТРОЕН', 'Employed')], default='АКТИВНО ИЩУ РАБОТУ', max_length=150, verbose_name='статус поиска работы')),
                ('image', models.ImageField(blank=True, upload_to='students/images', verbose_name='фото студента')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StudentHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.hardskill', verbose_name='навык студента')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='students.student', verbose_name='студент')),
            ],
            options={
                'verbose_name': 'навык студента',
                'verbose_name_plural': 'навыки студента',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.course', verbose_name='пройденные курсы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.student', verbose_name='студент курса')),
            ],
            options={
                'verbose_name': 'курс студента',
                'verbose_name_plural': 'курсы студента',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='course_list',
            field=models.ManyToManyField(related_name='student', through='students.StudentCourse', to='students.course', verbose_name='курсы студента'),
        ),
        migrations.AddField(
            model_name='student',
            name='hard_skills',
            field=models.ManyToManyField(related_name='student', through='students.StudentHardSkill', to='students.hardskill', verbose_name='навыки студента'),
        ),
        migrations.AddConstraint(
            model_name='studenthardskill',
            constraint=models.UniqueConstraint(fields=('student', 'hard_skill'), name='unique_student_hard_skill'),
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course'),
        ),
    ]
