# Generated by Django 4.1 on 2023-10-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'язык',
                'verbose_name_plural': 'языки',
            },
        ),
        migrations.CreateModel(
            name='StudentLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=150, verbose_name='уровень')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.language', verbose_name='язык')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='students.student', verbose_name='студент')),
            ],
            options={
                'verbose_name': 'уровень языка',
                'verbose_name_plural': 'уровни языков',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.ManyToManyField(blank=True, through='students.StudentLanguage', to='students.language', verbose_name='языки'),
        ),
    ]
