# Generated by Django 4.1 on 2023-10-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название курса')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='навыки студента')),
            ],
            options={
                'verbose_name': 'навык',
                'verbose_name_plural': 'навыки',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': 'студент', 'verbose_name_plural': 'студенты'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_list',
        ),
        migrations.AlterField(
            model_name='student',
            name='education',
            field=models.CharField(choices=[('НЕОКОЧЕННОЕ СРЕДНЕЕ', 'Incomplete Secondary'), ('СРЕДНЕЕ', 'Completed Secondary'), ('СРЕДНЕЕ ПРОФЕССИОНАЛЬНОЕ', 'Secondary Professional'), ('НЕОКОНЧЕННОЕ ВЫСШЕЕ', 'Incomplete Higher'), ('ВЫСШЕЕ', 'Completed Higher')], default='СРЕДНЕЕ', max_length=100, verbose_name='уровень образования'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='hard_skills',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('КУРС ПО ТРУДОУСТРОЙСТВУ', 'Employment Course'), ('ПРЕАКСЕЛЕРАЦИЯ', 'Preacceleration'), ('АКСЕЛЕРАЦИЯ', 'Acceleration'), ('ТРУДОСУСТРОЕН', 'Employed'), ('ОТЧИСЛЕН', 'Expelled')], default='АКСЕЛЕРАЦИЯ', max_length=100, verbose_name='статус в трекере'),
        ),
        migrations.CreateModel(
            name='StudentHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_student', to='students.hardskill', verbose_name='навык студента')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_skill', to='students.student', verbose_name='студенческий навык')),
            ],
            options={
                'verbose_name': 'навык студента',
                'verbose_name_plural': 'навыки студента',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_student', to='students.course', verbose_name='пройденные курсы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_course', to='students.student', verbose_name='студент курса')),
            ],
            options={
                'verbose_name': 'курс студента',
                'verbose_name_plural': 'курсы студента',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='course_list',
            field=models.ManyToManyField(related_name='student', through='students.StudentCourse', to='students.course', verbose_name='курсы студента'),
        ),
        migrations.AddField(
            model_name='student',
            name='hard_skills',
            field=models.ManyToManyField(related_name='student', through='students.StudentHardSkill', to='students.hardskill', verbose_name='навыки студента'),
        ),
        migrations.AddConstraint(
            model_name='studenthardskill',
            constraint=models.UniqueConstraint(fields=('student', 'hard_skill'), name='unique_student_hard_skill'),
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course'),
        ),
    ]
