# Generated by Django 4.1 on 2023-10-28 13:40

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_course_list_alter_student_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_location',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='students.location', verbose_name='местонахождение'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Неоконченное среднее'), (1, 'Среднее образование'), (2, 'Среднее профессиональное'), (3, 'Бакалавр'), (4, 'Магистр'), (5, 'Докторантура')], verbose_name='уровень образования'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hard_skills',
            field=models.ManyToManyField(to='students.hardskill', verbose_name='навыки'),
        ),
        migrations.AlterField(
            model_name='student',
            name='office_format',
            field=models.ManyToManyField(related_name='students', to='students.officeformat', verbose_name='форматы места работы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('actively_seeking', 'Активно ищу работу'), ('additional_work', 'Ищу дополнительную работу'), ('passively_seeking', 'Пассивно ищу работу'), ('open_to_offers', 'Открыт для предложений'), ('not_seeking', 'Не ищу работу')], max_length=150, verbose_name='статус поиска работы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=150, validators=[utils.validators.validate_telegram_username], verbose_name='телеграм'),
        ),
        migrations.AlterField(
            model_name='student',
            name='work_experience',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Без опыта'), (5, 'Менее 6 месяцев'), (9, 'Менее года'), (10, 'Один год'), (20, 'Два года'), (30, 'Три года'), (40, 'Четыре года'), (50, 'Пять лет'), (51, 'Более пяти лет')], verbose_name='опыт работы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='work_format',
            field=models.ManyToManyField(related_name='students', to='students.workformat', verbose_name='форматы работы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='work_schedule',
            field=models.ManyToManyField(related_name='students', to='students.workschedule', verbose_name='графики работы'),
        ),
    ]
