import os

from django.conf import settings

DATA_DIR = os.path.join(settings.BASE_DIR, 'data')

# константы для генерации студентов
STUDENTS_COUNT = 157
STUDENT_MIN_SALARY = 0
STUDENT_MAX_SALARY = 200
STUDENT_HARD_SKILLS_MIN = 3
STUDENT_HARD_SKILLS_MAX = 15
STUDENT_COURSES_MIN = 0
STUDENT_COURSES_MAX = 5
LOCATION_TO_RELOCATE_MIN = 0
LOCATION_TO_RELOCATE_MAX = 3
STUDENT_SPECIALITY_MIN = 1
STUDENT_SPECIALITY_MAX = 3
STUDENT_WORK_SCHEDULE_MIN = 1
STUDENT_WORK_SCHEDULE_MAX = 2
STUDENT_WORK_FORMAT_MIN = 1
STUDENT_WORK_FORMAT_MAX = 3
STUDENT_OFFICE_FORMAT_MIN = 1
STUDENT_OFFICE_FORMAT_MAX = 3
LANGUAGE_MIN = 0
LANGUAGE_MAX = 3
STUDENT_PORTFOLIO_URL = 'example.com/admin/portfolio.txt'
STUDENT_RESUME_URL = 'example.com/admin/cv.txt'

# для генерации вакансий
VACANCIES_COUNT = 57
VACANCY_MIN_SALARY = 20
VACANCY_MAX_SALARY = 300
VACANCY_HARD_SKILLS_MIN = 3
VACANCY_HARD_SKILLS_MAX = 15
VACANCY_COURSES_MIN = 0
VACANCY_COURSES_MAX = 5
VACANCY_LOCATIONS_MIN = 1
VACANCY_LOCATIONS_MAX = 5
VACANCY_WORK_SCHEDULE_MIN = 1
VACANCY_WORK_SCHEDULE_MAX = 2
VACANCY_WORK_FORMAT_MIN = 1
VACANCY_WORK_FORMAT_MAX = 3
VACANCY_GRADES_MIN = 0
VACANCY_GRADES_MAX = 2
VACANCY_ADMIN_AUTHOR = 9

USERS_COUNT = 7

CANDIDATES_COUNT = 300
