# Generated by Django 4.1 on 2023-10-24 15:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('salary_from', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='зарплата до')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='город')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='компания')),
                ('is_active', models.BooleanField(default=True, verbose_name='активная')),
                ('is_published', models.BooleanField(default=False, verbose_name='публичная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VacancyStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=5)], verbose_name='оценка студента на вакансию')),
                ('notes', models.TextField(blank=True, verbose_name='заметки HR по студенту на вакансию')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='students.student', verbose_name='студент')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='vacancies.vacancy', verbose_name='вакансия')),
            ],
            options={
                'verbose_name': 'претендент',
                'verbose_name_plural': 'претенденты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('id', 'ID'), ('first_name', 'имя студента'), ('last_name', 'фамилия студента'), ('location', 'местоположение'), ('education', 'уровень образования'), ('specialty', 'специальность'), ('status', 'статус поиска работы'), ('image', 'фото студента')], max_length=150, verbose_name='поле фильтра')),
                ('filter_value', models.CharField(max_length=150, verbose_name='значение фильтра')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='vacancies.vacancy', verbose_name='вакансия')),
            ],
        ),
    ]
