# Generated by Django 4.1 on 2023-10-26 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_experience',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Без опыта'), (5, 'Менее 6 месяцев'), (9, 'Менее года'), (10, 'Один год'), (20, 'Два года'), (30, 'Три года'), (40, 'Четыре года'), (50, 'Пять лет'), (51, 'Более пяти лет')], verbose_name='опыт работы'),
        ),
    ]
