# Generated by Django 4.1 on 2023-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_candidate_student_alter_candidate_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='portfolio',
            field=models.BooleanField(default=False, verbose_name='необходимо портфолио'),
        ),
    ]
