# Generated by Django 4.1 on 2023-10-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_language_studentlanguage_student_language'),
        ('vacancies', '0002_vacancy_language_vacancy_language_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacancyStudents',
            new_name='VacancyStudent',
        ),
    ]
