# Generated by Django 4.1 on 2023-10-28 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_current_location_and_more'),
        ('vacancies', '0003_alter_kanban_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='course_list',
            field=models.ManyToManyField(blank=True, to='students.course', verbose_name='курсы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Неоконченное среднее'), (1, 'Среднее образование'), (2, 'Среднее профессиональное'), (3, 'Бакалавр'), (4, 'Магистр'), (5, 'Докторантура')], verbose_name='уровень образования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.ManyToManyField(blank=True, to='students.location', verbose_name='местонахождения'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='office_format',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='students.officeformat', verbose_name='формат места работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_experience',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Без опыта'), (5, 'Менее 6 месяцев'), (9, 'Менее года'), (10, 'Один год'), (20, 'Два года'), (30, 'Три года'), (40, 'Четыре года'), (50, 'Пять лет'), (51, 'Более пяти лет')], verbose_name='опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancystudents',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=5)], verbose_name='оценка студента на вакансию'),
        ),
    ]
