# Generated by Django 4.1 on 2023-10-30 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_candidate_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='kanban_position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='vacancies.kanban', verbose_name='позиция в канбане'),
        ),
    ]
