# Generated by Django 4.1 on 2023-10-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_rename_vacancystudent_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ('id',), 'verbose_name': 'фильтр', 'verbose_name_plural': 'фильтры'},
        ),
    ]
